-- ============================================================
-- Futures parity — TS engine constants vs real SQL RPCs
-- ============================================================
-- Uses a deliberately non-round quantity input to prove that the SQL RPC stores
-- and settles with the same 6dp-quantized values produced by
-- packages/trading-engine/src/futures.ts.
-- ============================================================

BEGIN;

DO $$
DECLARE
  v_uid    UUID := gen_random_uuid();
  v_open   JSONB;
  v_close  JSONB;
  v_pos_id UUID;
  v_pos    futures_positions%ROWTYPE;
BEGIN
  INSERT INTO auth.users (id, aud, role, email, created_at, updated_at)
  VALUES (v_uid, 'authenticated', 'authenticated',
          'parity_' || v_uid::TEXT || '@test.local', NOW(), NOW());

  PERFORM set_config('phonara.ledger_write', 'allowed', true);
  UPDATE wallets SET usdt_available = '1000.000000' WHERE user_id = v_uid;
  PERFORM set_config('request.jwt.claims', json_build_object('sub', v_uid::TEXT)::TEXT, true);

  UPDATE app_config SET value = 'false' WHERE key IN ('system_halt', 'system_readonly');
  UPDATE app_config SET value = 'true' WHERE key IN ('feature_futures_enabled', 'consent_gate_enabled');
  INSERT INTO user_consents (user_id, doc_type, doc_version, accepted)
  SELECT v_uid, doc_type::consent_doc_type, 'test', TRUE
  FROM unnest(ARRAY['terms_of_service','privacy_policy','risk_disclosure','age_verification']) AS doc_type
  ON CONFLICT DO NOTHING;

  UPDATE futures_markets
     SET is_active = TRUE, max_leverage = 100, max_user_positions = 100, max_open_interest = '1000000.000000'
   WHERE symbol = 'PHONUSDT-PERP';
  UPDATE market_circuit_breakers SET is_halted = FALSE WHERE symbol = 'PHONUSDT-PERP';
  INSERT INTO oracle_prices (symbol, price, updated_at)
  VALUES ('PHONUSDT-PERP', '0.012345', NOW())
  ON CONFLICT (symbol) DO UPDATE SET price = '0.012345', updated_at = NOW();

  v_open := rpc_open_futures_position(
    'PHONUSDT-PERP',
    'long',
    'USDT',
    '123.456789',
    '7',
    NULL,
    NULL,
    'parity-' || v_uid::TEXT
  );
  v_pos_id := (v_open->>'position_id')::UUID;

  -- Expected constants generated by computeOpenPosition():
  -- quantity=70003.849574, openFee=0.518518, liquidationPrice=0.010643.
  ASSERT v_open->>'entry_price' = '0.012345', 'entry price parity failed: ' || v_open->>'entry_price';
  ASSERT v_open->>'quantity' = '70003.849574', 'quantity parity failed: ' || v_open->>'quantity';
  ASSERT v_open->>'notional' = '864.197523', 'notional parity failed: ' || v_open->>'notional';
  ASSERT v_open->>'open_fee' = '0.518518', 'open fee parity failed: ' || v_open->>'open_fee';
  ASSERT v_open->>'liquidation_price' = '0.010643',
    'liquidation price parity failed: ' || v_open->>'liquidation_price';

  SELECT * INTO v_pos FROM futures_positions WHERE id = v_pos_id;
  ASSERT v_pos.entry_price = '0.012345', 'stored entry price mismatch: ' || v_pos.entry_price;
  ASSERT v_pos.quantity = '70003.849574', 'stored quantity mismatch: ' || v_pos.quantity;
  ASSERT v_pos.open_fee = '0.518518', 'stored open fee mismatch: ' || v_pos.open_fee;
  ASSERT v_pos.liquidation_price = '0.010643',
    'stored liquidation price mismatch: ' || v_pos.liquidation_price;

  UPDATE oracle_prices SET price = '0.012900', updated_at = NOW()
   WHERE symbol = 'PHONUSDT-PERP';

  v_close := rpc_close_futures_position(v_pos_id);

  -- Expected constants generated by computeCloseSettlement() from the quantized
  -- position above.
  ASSERT v_close->>'exit_price' = '0.012900', 'exit price parity failed: ' || v_close->>'exit_price';
  ASSERT v_close->>'realized_pnl' = '38.852136',
    'realized PnL parity failed: ' || v_close->>'realized_pnl';
  ASSERT v_close->>'close_fee' = '0.541829', 'close fee parity failed: ' || v_close->>'close_fee';
  ASSERT v_close->>'equity_returned' = '161.767095',
    'equity parity failed: ' || v_close->>'equity_returned';

  ASSERT NOT EXISTS (SELECT 1 FROM verify_ledger_hash_chain(v_uid)),
    'wallet ledger hash chain broken after parity open/close';

  RAISE NOTICE 'FUTURES PARITY OK — TS constants match real SQL open/close RPCs';
END;
$$;

ROLLBACK;

BEGIN;

DO $$
DECLARE
  v_uid UUID := gen_random_uuid();
  v_market RECORD;
  v_side TEXT;
  v_entry NUMERIC;
  v_open JSONB;
  v_expected_liq NUMERIC;
  v_max_plus TEXT;
  v_rejected BOOLEAN;
  v_msg TEXT;
BEGIN
  INSERT INTO auth.users (id, aud, role, email, created_at, updated_at)
  VALUES (v_uid, 'authenticated', 'authenticated',
          'parity_maxlev_' || v_uid::TEXT || '@test.local', NOW(), NOW());
  PERFORM set_config('phonara.ledger_write', 'allowed', true);
  UPDATE wallets SET usdt_available = '1000000.000000' WHERE user_id = v_uid;
  PERFORM set_config('request.jwt.claims', json_build_object('sub', v_uid::TEXT)::TEXT, true);

  UPDATE app_config SET value = 'false' WHERE key IN ('system_halt', 'system_readonly');
  UPDATE app_config SET value = 'true' WHERE key IN ('feature_futures_enabled', 'consent_gate_enabled');
  UPDATE rpc_rate_limit_configs SET capacity = 100, refill_rate = 100 WHERE rpc_name = 'rpc_open_futures_position';
  INSERT INTO user_consents (user_id, doc_type, doc_version, accepted)
  SELECT v_uid, doc_type::consent_doc_type, 'test', TRUE
  FROM unnest(ARRAY['terms_of_service','privacy_policy','risk_disclosure','age_verification']) AS doc_type
  ON CONFLICT DO NOTHING;

  UPDATE futures_markets
     SET is_active = TRUE,
         max_user_positions = 100,
         max_open_interest = '1000000000.000000',
         min_notional = '1.000000'
   WHERE symbol IN ('PHONUSDT-PERP', 'BTCUSDT-SIM', 'ETHUSDT-SIM');
  UPDATE market_circuit_breakers
     SET is_halted = FALSE
   WHERE symbol IN ('PHONUSDT-PERP', 'BTCUSDT-SIM', 'ETHUSDT-SIM');

  INSERT INTO oracle_prices (symbol, price, updated_at)
  VALUES
    ('PHONUSDT-PERP', '0.012345', NOW()),
    ('BTCUSDT-SIM', '68000.123456', NOW()),
    ('ETHUSDT-SIM', '3500.654321', NOW())
  ON CONFLICT (symbol) DO UPDATE SET price = EXCLUDED.price, updated_at = NOW();

  FOR v_market IN
    SELECT symbol, max_leverage::NUMERIC AS max_leverage, maintenance_margin_rate::NUMERIC AS mmr
      FROM futures_markets
     WHERE symbol IN ('PHONUSDT-PERP', 'BTCUSDT-SIM', 'ETHUSDT-SIM')
     ORDER BY symbol
  LOOP
    SELECT price::NUMERIC INTO v_entry FROM oracle_prices WHERE symbol = v_market.symbol;

    FOREACH v_side IN ARRAY ARRAY['long', 'short']
    LOOP
      v_open := rpc_open_futures_position(
        v_market.symbol,
        v_side,
        'USDT',
        '123.456789',
        v_market.max_leverage::TEXT,
        NULL,
        NULL,
        'max-boundary-' || v_market.symbol || '-' || v_side || '-' || v_uid::TEXT
      );

      IF v_side = 'long' THEN
        v_expected_liq := v_entry * (1 - (1 / v_market.max_leverage) + v_market.mmr);
      ELSE
        v_expected_liq := v_entry * (1 + (1 / v_market.max_leverage) - v_market.mmr);
      END IF;
      IF v_expected_liq < 0 THEN v_expected_liq := 0; END IF;

      ASSERT v_open->>'liquidation_price' = _fmt6(v_expected_liq),
        format('%s %s max leverage liquidation parity failed: got=%s expected=%s',
          v_market.symbol, v_side, v_open->>'liquidation_price', _fmt6(v_expected_liq));
    END LOOP;

    v_max_plus := _fmt6(v_market.max_leverage + 0.000001);
    v_rejected := FALSE;
    BEGIN
      PERFORM rpc_open_futures_position(
        v_market.symbol,
        'long',
        'USDT',
        '123.456789',
        v_max_plus,
        NULL,
        NULL,
        'max-reject-' || v_market.symbol || '-' || v_uid::TEXT
      );
    EXCEPTION WHEN OTHERS THEN
      GET STACKED DIAGNOSTICS v_msg = MESSAGE_TEXT;
      IF v_msg = 'leverage_too_high' THEN v_rejected := TRUE; END IF;
    END;
    ASSERT v_rejected,
      format('%s just-over-max leverage must reject with leverage_too_high, got %s',
        v_market.symbol, COALESCE(v_msg, '<none>'));
  END LOOP;

  RAISE NOTICE 'FUTURES MAX LEVERAGE BOUNDARY OK — max parity and just-over-max rejection verified';
END;
$$;

ROLLBACK;

BEGIN;

DO $$
DECLARE
  v_uid UUID := gen_random_uuid();
  v_open JSONB;
  v_manual JSONB;
  v_pos_id UUID;
  v_liq NUMERIC;
  v_tick NUMERIC := 0.000001;
  v_blocked BOOLEAN;
  v_status position_status;
  v_msg TEXT;
BEGIN
  INSERT INTO auth.users (id, aud, role, email, created_at, updated_at)
  VALUES (v_uid, 'authenticated', 'authenticated',
          'parity_liq_boundary_' || v_uid::TEXT || '@test.local', NOW(), NOW());
  PERFORM set_config('phonara.ledger_write', 'allowed', true);
  UPDATE wallets SET usdt_available = '1000000.000000' WHERE user_id = v_uid;
  PERFORM set_config('request.jwt.claims', json_build_object('sub', v_uid::TEXT)::TEXT, true);

  UPDATE app_config SET value = 'false' WHERE key IN ('system_halt', 'system_readonly');
  UPDATE app_config SET value = 'true' WHERE key IN ('feature_futures_enabled', 'consent_gate_enabled');
  UPDATE rpc_rate_limit_configs
     SET capacity = 100, refill_rate = 100
   WHERE rpc_name IN ('rpc_open_futures_position', 'rpc_liquidate_position');
  INSERT INTO user_consents (user_id, doc_type, doc_version, accepted)
  SELECT v_uid, doc_type::consent_doc_type, 'test', TRUE
  FROM unnest(ARRAY['terms_of_service','privacy_policy','risk_disclosure','age_verification']) AS doc_type
  ON CONFLICT DO NOTHING;

  UPDATE futures_markets
     SET is_active = TRUE,
         max_leverage = '10',
         max_user_positions = 100,
         max_open_interest = '1000000000.000000',
         min_notional = '1.000000'
   WHERE symbol = 'PHONUSDT-PERP';
  UPDATE market_circuit_breakers SET is_halted = FALSE WHERE symbol = 'PHONUSDT-PERP';

  -- Long: one tick above liquidation price is not liquidatable.
  INSERT INTO oracle_prices (symbol, price, updated_at)
  VALUES ('PHONUSDT-PERP', '100.000000', NOW())
  ON CONFLICT (symbol) DO UPDATE SET price = '100.000000', updated_at = NOW();
  v_open := rpc_open_futures_position('PHONUSDT-PERP', 'long', 'USDT', '100.000000', '10', NULL, NULL,
    'liq-long-above-' || v_uid::TEXT);
  v_pos_id := (v_open->>'position_id')::UUID;
  v_liq := (v_open->>'liquidation_price')::NUMERIC;
  UPDATE oracle_prices SET price = _fmt6(v_liq + v_tick), updated_at = NOW() WHERE symbol = 'PHONUSDT-PERP';
  v_blocked := FALSE;
  BEGIN
    PERFORM rpc_liquidate_position(v_pos_id);
  EXCEPTION WHEN OTHERS THEN
    GET STACKED DIAGNOSTICS v_msg = MESSAGE_TEXT;
    IF v_msg = 'not_liquidatable' THEN v_blocked := TRUE; END IF;
  END;
  ASSERT v_blocked, format('long one tick above liq must not liquidate, got %s', COALESCE(v_msg, '<none>'));

  -- Long instant predicate: exact/below are breached, above is not.
  UPDATE oracle_prices SET price = '100.000000', updated_at = NOW() WHERE symbol = 'PHONUSDT-PERP';
  v_open := rpc_open_futures_position('PHONUSDT-PERP', 'long', 'USDT', '100.000000', '10', NULL, NULL,
    'liq-long-exact-' || v_uid::TEXT);
  v_pos_id := (v_open->>'position_id')::UUID;
  v_liq := (v_open->>'liquidation_price')::NUMERIC;
  ASSERT _is_liquidation_breached('long', v_liq, v_liq),
    'long exact liquidation predicate must be true';
  ASSERT _is_liquidation_breached('long', v_liq, v_liq - v_tick),
    'long one tick below liquidation predicate must be true';
  ASSERT NOT _is_liquidation_breached('long', v_liq, v_liq + v_tick),
    'long one tick above liquidation predicate must be false';

  -- SQL execution buffer: first breached tick records only; second breached tick settles.
  UPDATE oracle_prices SET price = _fmt6(v_liq), updated_at = NOW() WHERE symbol = 'PHONUSDT-PERP';
  INSERT INTO price_ticks (symbol, price, created_at)
  VALUES ('PHONUSDT-PERP', _fmt6(v_liq), NOW() + INTERVAL '1 second');
  v_manual := rpc_liquidate_position(v_pos_id);
  ASSERT v_manual->>'reason' = 'liquidation_buffer_pending',
    format('long first breached tick must return pending buffer state, got %s', v_manual);
  SELECT status INTO v_status FROM futures_positions WHERE id = v_pos_id;
  ASSERT v_status = 'open', 'long first breached tick must leave position open';

  UPDATE oracle_prices SET price = _fmt6(v_liq - v_tick), updated_at = NOW() WHERE symbol = 'PHONUSDT-PERP';
  INSERT INTO price_ticks (symbol, price, created_at)
  VALUES ('PHONUSDT-PERP', _fmt6(v_liq - v_tick), NOW() + INTERVAL '2 seconds');
  PERFORM rpc_liquidate_position(v_pos_id);
  SELECT status INTO v_status FROM futures_positions WHERE id = v_pos_id;
  ASSERT v_status = 'liquidated', 'long second breached tick must liquidate';

  -- Short: one tick below liquidation price is not liquidatable.
  UPDATE oracle_prices SET price = '100.000000', updated_at = NOW() WHERE symbol = 'PHONUSDT-PERP';
  v_open := rpc_open_futures_position('PHONUSDT-PERP', 'short', 'USDT', '100.000000', '10', NULL, NULL,
    'liq-short-below-' || v_uid::TEXT);
  v_pos_id := (v_open->>'position_id')::UUID;
  v_liq := (v_open->>'liquidation_price')::NUMERIC;
  UPDATE oracle_prices SET price = _fmt6(v_liq - v_tick), updated_at = NOW() WHERE symbol = 'PHONUSDT-PERP';
  v_blocked := FALSE;
  BEGIN
    PERFORM rpc_liquidate_position(v_pos_id);
  EXCEPTION WHEN OTHERS THEN
    GET STACKED DIAGNOSTICS v_msg = MESSAGE_TEXT;
    IF v_msg = 'not_liquidatable' THEN v_blocked := TRUE; END IF;
  END;
  ASSERT v_blocked, format('short one tick below liq must not liquidate, got %s', COALESCE(v_msg, '<none>'));

  -- Short instant predicate: exact/above are breached, below is not.
  UPDATE oracle_prices SET price = '100.000000', updated_at = NOW() WHERE symbol = 'PHONUSDT-PERP';
  v_open := rpc_open_futures_position('PHONUSDT-PERP', 'short', 'USDT', '100.000000', '10', NULL, NULL,
    'liq-short-exact-' || v_uid::TEXT);
  v_pos_id := (v_open->>'position_id')::UUID;
  v_liq := (v_open->>'liquidation_price')::NUMERIC;
  ASSERT _is_liquidation_breached('short', v_liq, v_liq),
    'short exact liquidation predicate must be true';
  ASSERT _is_liquidation_breached('short', v_liq, v_liq + v_tick),
    'short one tick above liquidation predicate must be true';
  ASSERT NOT _is_liquidation_breached('short', v_liq, v_liq - v_tick),
    'short one tick below liquidation predicate must be false';

  UPDATE oracle_prices SET price = _fmt6(v_liq), updated_at = NOW() WHERE symbol = 'PHONUSDT-PERP';
  INSERT INTO price_ticks (symbol, price, created_at)
  VALUES ('PHONUSDT-PERP', _fmt6(v_liq), NOW() + INTERVAL '3 seconds');
  v_manual := rpc_liquidate_position(v_pos_id);
  ASSERT v_manual->>'reason' = 'liquidation_buffer_pending',
    format('short first breached tick must return pending buffer state, got %s', v_manual);

  UPDATE oracle_prices SET price = _fmt6(v_liq + v_tick), updated_at = NOW() WHERE symbol = 'PHONUSDT-PERP';
  INSERT INTO price_ticks (symbol, price, created_at)
  VALUES ('PHONUSDT-PERP', _fmt6(v_liq + v_tick), NOW() + INTERVAL '4 seconds');
  PERFORM rpc_liquidate_position(v_pos_id);
  SELECT status INTO v_status FROM futures_positions WHERE id = v_pos_id;
  ASSERT v_status = 'liquidated', 'short second breached tick must liquidate';

  RAISE NOTICE 'FUTURES LIQUIDATION BOUNDARY OK — instant predicate parity and SQL two-tick buffer verified';
END;
$$;

ROLLBACK;

BEGIN;

DO $$
DECLARE
  v_uid    UUID := gen_random_uuid();
  v_open   JSONB;
  v_close  JSONB;
  v_pos_id UUID;
BEGIN
  INSERT INTO auth.users (id, aud, role, email, created_at, updated_at)
  VALUES (v_uid, 'authenticated', 'authenticated',
          'parity_short_' || v_uid::TEXT || '@test.local', NOW(), NOW());
  PERFORM set_config('phonara.ledger_write', 'allowed', true);
  UPDATE wallets SET usdt_available = '1000.000000' WHERE user_id = v_uid;
  PERFORM set_config('request.jwt.claims', json_build_object('sub', v_uid::TEXT)::TEXT, true);

  UPDATE app_config SET value = 'false' WHERE key IN ('system_halt', 'system_readonly');
  UPDATE app_config SET value = 'true' WHERE key IN ('feature_futures_enabled', 'consent_gate_enabled');
  INSERT INTO user_consents (user_id, doc_type, doc_version, accepted)
  SELECT v_uid, doc_type::consent_doc_type, 'test', TRUE
  FROM unnest(ARRAY['terms_of_service','privacy_policy','risk_disclosure','age_verification']) AS doc_type
  ON CONFLICT DO NOTHING;

  UPDATE futures_markets
     SET is_active = TRUE, max_leverage = 100, max_user_positions = 100, max_open_interest = '1000000.000000'
   WHERE symbol = 'PHONUSDT-PERP';
  UPDATE market_circuit_breakers SET is_halted = FALSE WHERE symbol = 'PHONUSDT-PERP';
  INSERT INTO oracle_prices (symbol, price, updated_at)
  VALUES ('PHONUSDT-PERP', '0.012345', NOW())
  ON CONFLICT (symbol) DO UPDATE SET price = '0.012345', updated_at = NOW();

  v_open := rpc_open_futures_position(
    'PHONUSDT-PERP', 'short', 'USDT', '123.456789', '7',
    NULL, NULL, 'parity-short-' || v_uid::TEXT
  );
  v_pos_id := (v_open->>'position_id')::UUID;

  ASSERT v_open->>'quantity' = '70003.849574', 'short quantity parity failed';
  ASSERT v_open->>'liquidation_price' = '0.014046',
    'short liquidation price parity failed';

  UPDATE oracle_prices SET price = '0.011900', updated_at = NOW()
   WHERE symbol = 'PHONUSDT-PERP';
  v_close := rpc_close_futures_position(v_pos_id);

  ASSERT v_close->>'realized_pnl' = '31.151713',
    'short profit PnL parity failed';
  ASSERT v_close->>'close_fee' = '0.499827', 'short close fee parity failed';
  ASSERT v_close->>'equity_returned' = '154.108674',
    'short equity parity failed';

  RAISE NOTICE 'FUTURES SHORT PARITY OK — short profit constants match SQL math';
END;
$$;

ROLLBACK;

BEGIN;

DO $$
DECLARE
  v_uid    UUID := gen_random_uuid();
  v_open   JSONB;
  v_close  JSONB;
  v_pos_id UUID;
BEGIN
  INSERT INTO auth.users (id, aud, role, email, created_at, updated_at)
  VALUES (v_uid, 'authenticated', 'authenticated',
          'parity_loss_' || v_uid::TEXT || '@test.local', NOW(), NOW());
  PERFORM set_config('phonara.ledger_write', 'allowed', true);
  UPDATE wallets SET usdt_available = '1000.000000' WHERE user_id = v_uid;
  PERFORM set_config('request.jwt.claims', json_build_object('sub', v_uid::TEXT)::TEXT, true);

  UPDATE app_config SET value = 'false' WHERE key IN ('system_halt', 'system_readonly');
  UPDATE app_config SET value = 'true' WHERE key IN ('feature_futures_enabled', 'consent_gate_enabled');
  INSERT INTO user_consents (user_id, doc_type, doc_version, accepted)
  SELECT v_uid, doc_type::consent_doc_type, 'test', TRUE
  FROM unnest(ARRAY['terms_of_service','privacy_policy','risk_disclosure','age_verification']) AS doc_type
  ON CONFLICT DO NOTHING;

  UPDATE futures_markets
     SET is_active = TRUE, max_leverage = 100, max_user_positions = 100, max_open_interest = '1000000.000000'
   WHERE symbol = 'PHONUSDT-PERP';
  UPDATE market_circuit_breakers SET is_halted = FALSE WHERE symbol = 'PHONUSDT-PERP';
  INSERT INTO oracle_prices (symbol, price, updated_at)
  VALUES ('PHONUSDT-PERP', '0.012345', NOW())
  ON CONFLICT (symbol) DO UPDATE SET price = '0.012345', updated_at = NOW();

  v_open := rpc_open_futures_position(
    'PHONUSDT-PERP', 'long', 'USDT', '123.456789', '7',
    NULL, NULL, 'parity-loss-' || v_uid::TEXT
  );
  v_pos_id := (v_open->>'position_id')::UUID;

  UPDATE oracle_prices SET price = '0.012000', updated_at = NOW()
   WHERE symbol = 'PHONUSDT-PERP';
  v_close := rpc_close_futures_position(v_pos_id);

  ASSERT v_close->>'realized_pnl' = '-24.151328',
    'long loss PnL parity failed';
  ASSERT v_close->>'close_fee' = '0.504027', 'long loss close fee parity failed';
  ASSERT v_close->>'equity_returned' = '98.801433',
    'long loss equity parity failed';

  RAISE NOTICE 'FUTURES LOSS PARITY OK — long loss constants match SQL math';
END;
$$;

ROLLBACK;

BEGIN;

DO $$
DECLARE
  v_uid    UUID := gen_random_uuid();
  v_open   JSONB;
  v_close  JSONB;
  v_pos_id UUID;
BEGIN
  INSERT INTO auth.users (id, aud, role, email, created_at, updated_at)
  VALUES (v_uid, 'authenticated', 'authenticated',
          'parity_wipeout_' || v_uid::TEXT || '@test.local', NOW(), NOW());
  PERFORM set_config('phonara.ledger_write', 'allowed', true);
  UPDATE wallets SET usdt_available = '1000.000000' WHERE user_id = v_uid;
  PERFORM set_config('request.jwt.claims', json_build_object('sub', v_uid::TEXT)::TEXT, true);

  UPDATE app_config SET value = 'false' WHERE key IN ('system_halt', 'system_readonly');
  UPDATE app_config SET value = 'true' WHERE key IN ('feature_futures_enabled', 'consent_gate_enabled');
  INSERT INTO user_consents (user_id, doc_type, doc_version, accepted)
  SELECT v_uid, doc_type::consent_doc_type, 'test', TRUE
  FROM unnest(ARRAY['terms_of_service','privacy_policy','risk_disclosure','age_verification']) AS doc_type
  ON CONFLICT DO NOTHING;

  UPDATE futures_markets
     SET is_active = TRUE, max_leverage = 100, max_user_positions = 100, max_open_interest = '1000000.000000'
   WHERE symbol = 'PHONUSDT-PERP';
  UPDATE market_circuit_breakers SET is_halted = FALSE WHERE symbol = 'PHONUSDT-PERP';
  INSERT INTO oracle_prices (symbol, price, updated_at)
  VALUES ('PHONUSDT-PERP', '100.000000', NOW())
  ON CONFLICT (symbol) DO UPDATE SET price = '100.000000', updated_at = NOW();

  v_open := rpc_open_futures_position(
    'PHONUSDT-PERP', 'long', 'USDT', '100.000000', '10',
    NULL, NULL, 'parity-wipeout-' || v_uid::TEXT
  );
  v_pos_id := (v_open->>'position_id')::UUID;

  UPDATE oracle_prices SET price = '80.000000', updated_at = NOW()
   WHERE symbol = 'PHONUSDT-PERP';
  v_close := rpc_close_futures_position(v_pos_id);

  ASSERT v_close->>'realized_pnl' = '-200.000000',
    'wipeout PnL parity failed';
  ASSERT v_close->>'close_fee' = '0.480000', 'wipeout close fee parity failed';
  ASSERT v_close->>'equity_returned' = '0.000000',
    'wipeout equity parity failed';

  RAISE NOTICE 'FUTURES WIPEOUT PARITY OK — equity floor constants match SQL math';
END;
$$;

ROLLBACK;
