-- ============================================================
-- Futures parity — TS engine constants vs real SQL RPCs
-- ============================================================
-- Uses a deliberately non-round quantity input to prove that the SQL RPC stores
-- and settles with the same 6dp-quantized values produced by
-- packages/trading-engine/src/futures.ts.
-- ============================================================

BEGIN;

DO $$
DECLARE
  v_uid    UUID := gen_random_uuid();
  v_open   JSONB;
  v_close  JSONB;
  v_pos_id UUID;
  v_pos    futures_positions%ROWTYPE;
BEGIN
  INSERT INTO auth.users (id, aud, role, email, created_at, updated_at)
  VALUES (v_uid, 'authenticated', 'authenticated',
          'parity_' || v_uid::TEXT || '@test.local', NOW(), NOW());

  UPDATE wallets SET usdt_available = '1000.000000' WHERE user_id = v_uid;
  PERFORM set_config('request.jwt.claims', json_build_object('sub', v_uid::TEXT)::TEXT, true);

  UPDATE app_config SET value = 'false' WHERE key IN ('system_halt', 'system_readonly');
  UPDATE app_config SET value = 'true' WHERE key IN ('feature_futures_enabled', 'consent_gate_enabled');
  INSERT INTO user_consents (user_id, doc_type, doc_version, accepted)
  SELECT v_uid, doc_type::consent_doc_type, 'test', TRUE
  FROM unnest(ARRAY['terms_of_service','privacy_policy','risk_disclosure','age_verification']) AS doc_type
  ON CONFLICT DO NOTHING;

  UPDATE futures_markets
     SET is_active = TRUE, max_leverage = 100, max_user_positions = 100, max_open_interest = '1000000.000000'
   WHERE symbol = 'PHONUSDT-PERP';
  UPDATE market_circuit_breakers SET is_halted = FALSE WHERE symbol = 'PHONUSDT-PERP';
  INSERT INTO oracle_prices (symbol, price, updated_at)
  VALUES ('PHONUSDT-PERP', '0.012345', NOW())
  ON CONFLICT (symbol) DO UPDATE SET price = '0.012345', updated_at = NOW();

  v_open := rpc_open_futures_position(
    'PHONUSDT-PERP',
    'long',
    'USDT',
    '123.456789',
    '7',
    NULL,
    NULL,
    'parity-' || v_uid::TEXT
  );
  v_pos_id := (v_open->>'position_id')::UUID;

  -- Expected constants generated by computeOpenPosition():
  -- quantity=70003.849574, openFee=0.518518, liquidationPrice=0.010643.
  ASSERT v_open->>'entry_price' = '0.012345', 'entry price parity failed: ' || v_open->>'entry_price';
  ASSERT v_open->>'quantity' = '70003.849574', 'quantity parity failed: ' || v_open->>'quantity';
  ASSERT v_open->>'notional' = '864.197523', 'notional parity failed: ' || v_open->>'notional';
  ASSERT v_open->>'open_fee' = '0.518518', 'open fee parity failed: ' || v_open->>'open_fee';
  ASSERT v_open->>'liquidation_price' = '0.010643',
    'liquidation price parity failed: ' || v_open->>'liquidation_price';

  SELECT * INTO v_pos FROM futures_positions WHERE id = v_pos_id;
  ASSERT v_pos.entry_price = '0.012345', 'stored entry price mismatch: ' || v_pos.entry_price;
  ASSERT v_pos.quantity = '70003.849574', 'stored quantity mismatch: ' || v_pos.quantity;
  ASSERT v_pos.open_fee = '0.518518', 'stored open fee mismatch: ' || v_pos.open_fee;
  ASSERT v_pos.liquidation_price = '0.010643',
    'stored liquidation price mismatch: ' || v_pos.liquidation_price;

  UPDATE oracle_prices SET price = '0.012900', updated_at = NOW()
   WHERE symbol = 'PHONUSDT-PERP';

  v_close := rpc_close_futures_position(v_pos_id);

  -- Expected constants generated by computeCloseSettlement() from the quantized
  -- position above.
  ASSERT v_close->>'exit_price' = '0.012900', 'exit price parity failed: ' || v_close->>'exit_price';
  ASSERT v_close->>'realized_pnl' = '38.852136',
    'realized PnL parity failed: ' || v_close->>'realized_pnl';
  ASSERT v_close->>'close_fee' = '0.541829', 'close fee parity failed: ' || v_close->>'close_fee';
  ASSERT v_close->>'equity_returned' = '161.767095',
    'equity parity failed: ' || v_close->>'equity_returned';

  ASSERT NOT EXISTS (SELECT 1 FROM verify_ledger_hash_chain(v_uid)),
    'wallet ledger hash chain broken after parity open/close';

  RAISE NOTICE 'FUTURES PARITY OK — TS constants match real SQL open/close RPCs';
END;
$$;

ROLLBACK;

BEGIN;

DO $$
DECLARE
  v_uid    UUID := gen_random_uuid();
  v_open   JSONB;
  v_close  JSONB;
  v_pos_id UUID;
BEGIN
  INSERT INTO auth.users (id, aud, role, email, created_at, updated_at)
  VALUES (v_uid, 'authenticated', 'authenticated',
          'parity_short_' || v_uid::TEXT || '@test.local', NOW(), NOW());
  UPDATE wallets SET usdt_available = '1000.000000' WHERE user_id = v_uid;
  PERFORM set_config('request.jwt.claims', json_build_object('sub', v_uid::TEXT)::TEXT, true);

  UPDATE app_config SET value = 'false' WHERE key IN ('system_halt', 'system_readonly');
  UPDATE app_config SET value = 'true' WHERE key IN ('feature_futures_enabled', 'consent_gate_enabled');
  INSERT INTO user_consents (user_id, doc_type, doc_version, accepted)
  SELECT v_uid, doc_type::consent_doc_type, 'test', TRUE
  FROM unnest(ARRAY['terms_of_service','privacy_policy','risk_disclosure','age_verification']) AS doc_type
  ON CONFLICT DO NOTHING;

  UPDATE futures_markets
     SET is_active = TRUE, max_leverage = 100, max_user_positions = 100, max_open_interest = '1000000.000000'
   WHERE symbol = 'PHONUSDT-PERP';
  UPDATE market_circuit_breakers SET is_halted = FALSE WHERE symbol = 'PHONUSDT-PERP';
  INSERT INTO oracle_prices (symbol, price, updated_at)
  VALUES ('PHONUSDT-PERP', '0.012345', NOW())
  ON CONFLICT (symbol) DO UPDATE SET price = '0.012345', updated_at = NOW();

  v_open := rpc_open_futures_position(
    'PHONUSDT-PERP', 'short', 'USDT', '123.456789', '7',
    NULL, NULL, 'parity-short-' || v_uid::TEXT
  );
  v_pos_id := (v_open->>'position_id')::UUID;

  ASSERT v_open->>'quantity' = '70003.849574', 'short quantity parity failed';
  ASSERT v_open->>'liquidation_price' = '0.014046',
    'short liquidation price parity failed';

  UPDATE oracle_prices SET price = '0.011900', updated_at = NOW()
   WHERE symbol = 'PHONUSDT-PERP';
  v_close := rpc_close_futures_position(v_pos_id);

  ASSERT v_close->>'realized_pnl' = '31.151713',
    'short profit PnL parity failed';
  ASSERT v_close->>'close_fee' = '0.499827', 'short close fee parity failed';
  ASSERT v_close->>'equity_returned' = '154.108674',
    'short equity parity failed';

  RAISE NOTICE 'FUTURES SHORT PARITY OK — short profit constants match SQL math';
END;
$$;

ROLLBACK;

BEGIN;

DO $$
DECLARE
  v_uid    UUID := gen_random_uuid();
  v_open   JSONB;
  v_close  JSONB;
  v_pos_id UUID;
BEGIN
  INSERT INTO auth.users (id, aud, role, email, created_at, updated_at)
  VALUES (v_uid, 'authenticated', 'authenticated',
          'parity_loss_' || v_uid::TEXT || '@test.local', NOW(), NOW());
  UPDATE wallets SET usdt_available = '1000.000000' WHERE user_id = v_uid;
  PERFORM set_config('request.jwt.claims', json_build_object('sub', v_uid::TEXT)::TEXT, true);

  UPDATE app_config SET value = 'false' WHERE key IN ('system_halt', 'system_readonly');
  UPDATE app_config SET value = 'true' WHERE key IN ('feature_futures_enabled', 'consent_gate_enabled');
  INSERT INTO user_consents (user_id, doc_type, doc_version, accepted)
  SELECT v_uid, doc_type::consent_doc_type, 'test', TRUE
  FROM unnest(ARRAY['terms_of_service','privacy_policy','risk_disclosure','age_verification']) AS doc_type
  ON CONFLICT DO NOTHING;

  UPDATE futures_markets
     SET is_active = TRUE, max_leverage = 100, max_user_positions = 100, max_open_interest = '1000000.000000'
   WHERE symbol = 'PHONUSDT-PERP';
  UPDATE market_circuit_breakers SET is_halted = FALSE WHERE symbol = 'PHONUSDT-PERP';
  INSERT INTO oracle_prices (symbol, price, updated_at)
  VALUES ('PHONUSDT-PERP', '0.012345', NOW())
  ON CONFLICT (symbol) DO UPDATE SET price = '0.012345', updated_at = NOW();

  v_open := rpc_open_futures_position(
    'PHONUSDT-PERP', 'long', 'USDT', '123.456789', '7',
    NULL, NULL, 'parity-loss-' || v_uid::TEXT
  );
  v_pos_id := (v_open->>'position_id')::UUID;

  UPDATE oracle_prices SET price = '0.012000', updated_at = NOW()
   WHERE symbol = 'PHONUSDT-PERP';
  v_close := rpc_close_futures_position(v_pos_id);

  ASSERT v_close->>'realized_pnl' = '-24.151328',
    'long loss PnL parity failed';
  ASSERT v_close->>'close_fee' = '0.504027', 'long loss close fee parity failed';
  ASSERT v_close->>'equity_returned' = '98.801433',
    'long loss equity parity failed';

  RAISE NOTICE 'FUTURES LOSS PARITY OK — long loss constants match SQL math';
END;
$$;

ROLLBACK;

BEGIN;

DO $$
DECLARE
  v_uid    UUID := gen_random_uuid();
  v_open   JSONB;
  v_close  JSONB;
  v_pos_id UUID;
BEGIN
  INSERT INTO auth.users (id, aud, role, email, created_at, updated_at)
  VALUES (v_uid, 'authenticated', 'authenticated',
          'parity_wipeout_' || v_uid::TEXT || '@test.local', NOW(), NOW());
  UPDATE wallets SET usdt_available = '1000.000000' WHERE user_id = v_uid;
  PERFORM set_config('request.jwt.claims', json_build_object('sub', v_uid::TEXT)::TEXT, true);

  UPDATE app_config SET value = 'false' WHERE key IN ('system_halt', 'system_readonly');
  UPDATE app_config SET value = 'true' WHERE key IN ('feature_futures_enabled', 'consent_gate_enabled');
  INSERT INTO user_consents (user_id, doc_type, doc_version, accepted)
  SELECT v_uid, doc_type::consent_doc_type, 'test', TRUE
  FROM unnest(ARRAY['terms_of_service','privacy_policy','risk_disclosure','age_verification']) AS doc_type
  ON CONFLICT DO NOTHING;

  UPDATE futures_markets
     SET is_active = TRUE, max_leverage = 100, max_user_positions = 100, max_open_interest = '1000000.000000'
   WHERE symbol = 'PHONUSDT-PERP';
  UPDATE market_circuit_breakers SET is_halted = FALSE WHERE symbol = 'PHONUSDT-PERP';
  INSERT INTO oracle_prices (symbol, price, updated_at)
  VALUES ('PHONUSDT-PERP', '100.000000', NOW())
  ON CONFLICT (symbol) DO UPDATE SET price = '100.000000', updated_at = NOW();

  v_open := rpc_open_futures_position(
    'PHONUSDT-PERP', 'long', 'USDT', '100.000000', '10',
    NULL, NULL, 'parity-wipeout-' || v_uid::TEXT
  );
  v_pos_id := (v_open->>'position_id')::UUID;

  UPDATE oracle_prices SET price = '80.000000', updated_at = NOW()
   WHERE symbol = 'PHONUSDT-PERP';
  v_close := rpc_close_futures_position(v_pos_id);

  ASSERT v_close->>'realized_pnl' = '-200.000000',
    'wipeout PnL parity failed';
  ASSERT v_close->>'close_fee' = '0.480000', 'wipeout close fee parity failed';
  ASSERT v_close->>'equity_returned' = '0.000000',
    'wipeout equity parity failed';

  RAISE NOTICE 'FUTURES WIPEOUT PARITY OK — equity floor constants match SQL math';
END;
$$;

ROLLBACK;
