-- ============================================================
-- E foundation ①-2 (audit A8-2) — system_account_ledger hash-chain
-- ============================================================
-- Why: ①-1 (000045) made system_account_ledger append-only (DO INSTEAD NOTHING
-- RULEs) and revoked direct client writes. This migration adds the wallet-grade
-- SIGNED hash-chain so any mutation that BYPASSES the RULE (RULE disabled,
-- superuser, or a buggy/compromised migration) is detectable by an auditor.
--
-- The E insurance fund / fee / liquidity / dust legs write here via
-- _credit_system_account / _debit_system_account. Their bodies are UNCHANGED —
-- the BEFORE INSERT trigger signs every appended row automatically.
--
-- Chain model (vs wallet_ledger):
--   chain unit = account_code      (wallet_ledger = user_id)
--   order key  = global IDENTITY seq (same pattern as wallet_ledger)
--   serialization = _credit/_debit hold `system_accounts FOR UPDATE`, so inserts
--                   for the SAME account_code are serialized → no chain fork.
--   payload    = _sal_row_hash(...) — the ONLY place the payload is built, shared
--                by the trigger, the verifier, and the one-time backfill so they
--                can never drift (the wallet v1→v2 lesson, 000017).
--
-- v1 payload (final). We sign the attribution fields (related_user_id,
-- related_tx_id, transfer_id) NOW rather than deferring to a v2: 000017 proved
-- that leaving identity/attribution fields OUTSIDE the signed payload is a tamper
-- hole, and a later re-hash migration (DISABLE RULE → rewrite all rows) is
-- exactly the kind of work this avoids. Cost is two extra args + coalesce.
--
--   prev_hash | id | account_code | direction | currency | amount |
--   balance_before | balance_after | reason_code |
--   related_user_id | related_tx_id | transfer_id | seq
--
-- All NULLABLE fields (related_user_id, related_tx_id, transfer_id) are coalesced
-- to '' INSIDE the helper. Without this, a single NULL would make the whole
-- concatenation NULL → row_hash NULL → the chain silently becomes unverifiable.
--
-- NOT in scope here (kept separate so RED never mixes "chain" with "settlement"):
--   * rpc_run_reconciliation auto-verify wiring + system Σ=0  → ①-3 (A2-3/A8-3)
--   * wallet verify_ledger_hash_chain cron wiring             → ①-3
--   * system_accounts.balance chain (balance is a mutable aggregate; only the
--     append-only ledger is chained — same boundary as ①-1).
--
-- Local-only until Wave 12. No remote apply in this change.
-- ============================================================

-- ─────────────────────────────────────────────────────────────────────────────
-- 1. Chain columns (mirror wallet_ledger A4) + chain-walk index
-- ─────────────────────────────────────────────────────────────────────────────
-- seq is assigned by the IDENTITY default BEFORE the BEFORE-INSERT trigger runs,
-- so NEW.seq is available to the trigger. Chain order = per-account ascending seq.
ALTER TABLE system_account_ledger
  ADD COLUMN IF NOT EXISTS seq       BIGINT GENERATED BY DEFAULT AS IDENTITY,
  ADD COLUMN IF NOT EXISTS prev_hash TEXT,
  ADD COLUMN IF NOT EXISTS row_hash  TEXT;

CREATE INDEX IF NOT EXISTS sal_hash_chain_idx ON system_account_ledger (account_code, seq);

-- ─────────────────────────────────────────────────────────────────────────────
-- 2. Single source of truth for the row payload → SHA-256 hex digest
-- ─────────────────────────────────────────────────────────────────────────────
CREATE OR REPLACE FUNCTION _sal_row_hash(
  p_prev_hash       TEXT,
  p_id              UUID,
  p_account_code    TEXT,
  p_direction       TEXT,
  p_currency        TEXT,
  p_amount          TEXT,
  p_balance_before  TEXT,
  p_balance_after   TEXT,
  p_reason_code     TEXT,
  p_related_user_id UUID,
  p_related_tx_id   TEXT,
  p_transfer_id     UUID,
  p_seq             BIGINT
)
RETURNS TEXT
LANGUAGE sql
IMMUTABLE
SET search_path = public, pg_temp
AS $$
  SELECT encode(
    extensions.digest(
      coalesce(p_prev_hash, 'GENESIS')
        || '|' || p_id::TEXT
        || '|' || p_account_code
        || '|' || p_direction
        || '|' || p_currency
        || '|' || p_amount
        || '|' || p_balance_before
        || '|' || p_balance_after
        || '|' || p_reason_code
        || '|' || coalesce(p_related_user_id::TEXT, '')
        || '|' || coalesce(p_related_tx_id, '')
        || '|' || coalesce(p_transfer_id::TEXT, '')
        || '|' || p_seq::TEXT,
      'sha256'
    ),
    'hex'
  );
$$;

-- Internal primitive: the SECURITY DEFINER trigger/verifier call it as owner.
REVOKE ALL ON FUNCTION
  _sal_row_hash(TEXT, UUID, TEXT, TEXT, TEXT, TEXT, TEXT, TEXT, TEXT, UUID, TEXT, UUID, BIGINT)
  FROM PUBLIC, anon, authenticated;

-- ─────────────────────────────────────────────────────────────────────────────
-- 3. BEFORE INSERT trigger signs the row via the shared helper
-- ─────────────────────────────────────────────────────────────────────────────
-- Concurrent inserts for the SAME account_code are serialized by the
-- `system_accounts FOR UPDATE` lock held in _credit/_debit_system_account, so the
-- "previous row for this account" lookup never races into a fork.
CREATE OR REPLACE FUNCTION _sal_compute_hash()
RETURNS TRIGGER
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public, pg_temp
AS $$
DECLARE
  v_prev_hash TEXT;
BEGIN
  SELECT row_hash INTO v_prev_hash
  FROM system_account_ledger
  WHERE account_code = NEW.account_code
    AND seq < NEW.seq
  ORDER BY seq DESC
  LIMIT 1;

  NEW.prev_hash := v_prev_hash;   -- NULL if first row for this account
  NEW.row_hash  := _sal_row_hash(
    v_prev_hash,
    NEW.id,
    NEW.account_code,
    NEW.direction,
    NEW.currency::TEXT,
    NEW.amount,
    NEW.balance_before,
    NEW.balance_after,
    NEW.reason_code,
    NEW.related_user_id,
    NEW.related_tx_id,
    NEW.transfer_id,
    NEW.seq
  );
  RETURN NEW;
END;
$$;

CREATE TRIGGER trg_sal_hash_chain
BEFORE INSERT ON system_account_ledger
FOR EACH ROW EXECUTE FUNCTION _sal_compute_hash();

-- ─────────────────────────────────────────────────────────────────────────────
-- 4. Verifier — recomputes the payload (same helper) and reports broken rows
-- ─────────────────────────────────────────────────────────────────────────────
-- Returns one row per broken entry; empty result = clean. Chain resets at each
-- account_code boundary (tracked across loop iterations), mirroring the wallet
-- verifier's per-user reset.
CREATE OR REPLACE FUNCTION verify_system_account_hash_chain(p_account_code TEXT DEFAULT NULL)
RETURNS TABLE (
  broken_account_code TEXT,
  entry_id            UUID,
  entry_seq           BIGINT,
  expected            TEXT,
  actual              TEXT
)
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public, pg_temp
AS $$
DECLARE
  r              system_account_ledger%ROWTYPE;
  v_last_account TEXT := NULL;
  v_prev_hash    TEXT := NULL;
  v_expected     TEXT;
BEGIN
  FOR r IN
    SELECT * FROM system_account_ledger
    WHERE (p_account_code IS NULL OR system_account_ledger.account_code = p_account_code)
    ORDER BY system_account_ledger.account_code, system_account_ledger.seq
  LOOP
    -- Reset chain when we cross into a new account's first row
    IF v_last_account IS NULL OR r.account_code <> v_last_account THEN
      v_prev_hash := NULL;
      v_last_account := r.account_code;
    END IF;

    v_expected := _sal_row_hash(
      v_prev_hash, r.id, r.account_code, r.direction, r.currency::TEXT, r.amount,
      r.balance_before, r.balance_after, r.reason_code,
      r.related_user_id, r.related_tx_id, r.transfer_id, r.seq
    );

    -- Detect both tampered fields (hash mismatch) and a broken prev_hash link
    IF v_expected <> coalesce(r.row_hash, '')
       OR coalesce(r.prev_hash, '') <> coalesce(v_prev_hash, '') THEN
      broken_account_code := r.account_code;
      entry_id            := r.id;
      entry_seq           := r.seq;
      expected            := v_expected;
      actual              := r.row_hash;
      RETURN NEXT;
    END IF;

    v_prev_hash := r.row_hash;
  END LOOP;
END;
$$;

-- ─────────────────────────────────────────────────────────────────────────────
-- 5. One-time deterministic backfill of any existing rows (000017 pattern)
-- ─────────────────────────────────────────────────────────────────────────────
-- The append-only RULE must be disabled for this controlled rewrite, then
-- re-enabled. The BEFORE-INSERT trigger does not fire on UPDATE, so the chain is
-- rebuilt purely from the shared helper. (At a clean reset the ledger is empty,
-- so this is a no-op; it exists so the chain stays correct if rows ever predate
-- this migration.)
ALTER TABLE system_account_ledger DISABLE RULE system_account_ledger_no_update;
DO $$
DECLARE
  r              system_account_ledger%ROWTYPE;
  v_last_account TEXT := NULL;
  v_prev_hash    TEXT := NULL;
  v_hash         TEXT;
BEGIN
  FOR r IN SELECT * FROM system_account_ledger ORDER BY account_code, seq LOOP
    IF v_last_account IS NULL OR r.account_code <> v_last_account THEN
      v_prev_hash := NULL;
      v_last_account := r.account_code;
    END IF;

    v_hash := _sal_row_hash(
      v_prev_hash, r.id, r.account_code, r.direction, r.currency::TEXT, r.amount,
      r.balance_before, r.balance_after, r.reason_code,
      r.related_user_id, r.related_tx_id, r.transfer_id, r.seq
    );

    UPDATE system_account_ledger SET prev_hash = v_prev_hash, row_hash = v_hash WHERE id = r.id;

    v_prev_hash := v_hash;
  END LOOP;
END;
$$;
ALTER TABLE system_account_ledger ENABLE RULE system_account_ledger_no_update;

-- ─────────────────────────────────────────────────────────────────────────────
-- 6. Lockdown (000010 REVOKE pattern). search_path is pinned in each function
--    header above (000013 belt), so no separate ALTER FUNCTION pass is needed.
-- ─────────────────────────────────────────────────────────────────────────────
-- _sal_compute_hash: trigger fn, never called via API.
-- verify_system_account_hash_chain: audit/cron-only info-disclosure (admin reads
--   system_account_ledger via RLS; the verifier runs as definer for reconciliation
--   in ①-3). Neither anon nor authenticated may EXECUTE it.
REVOKE ALL ON FUNCTION _sal_compute_hash()                         FROM PUBLIC, anon, authenticated;
REVOKE ALL ON FUNCTION verify_system_account_hash_chain(TEXT)      FROM PUBLIC, anon, authenticated;
